// Generated by https://quicktype.io

export interface IEnergyBalanceMonthQuarter {
	'sma.sunnyportal.services': SMASunnyportalServices;
}

export interface SMASunnyportalServices {
	service: Service;
}

export interface Service {
	$: ServiceClass;
	data: Data;
}

export interface ServiceClass {
	name: string;
	method: string;
	version: string;
	'request-oid': string;
	'creation-date': string;
}

export interface Data {
	energybalance: EnergybalanceClass;
}

export interface EnergybalanceClass {
	$: Energybalance;
	month: MonthClass;
}

export interface Energybalance {
	unit: string;
}

export interface MonthClass {
	$: Month;
	hour: Array<HourClass | string>;
}

export interface Month {
	timestamp: string;
}

export interface HourClass {
	$: Hour;
}

export interface Hour {
	timestamp: string;
	'battery-charging': string;
	'battery-discharging': string;
	'direct-consumption': string;
	'external-supply': string;
	'feed-in': string;
	'pv-generation'?: string;
	'self-consumption': string;
	'self-supply': string;
}
