// Generated by https://quicktype.io

export interface IMonthOverview {
	'sma.sunnyportal.services': SMASunnyportalServices;
}

export interface SMASunnyportalServices {
	service: Service;
}

export interface Service {
	$: ServiceClass;
	data: Data;
}

export interface ServiceClass {
	name: string;
	method: string;
	version: string;
	'request-oid': string;
	'creation-date': string;
}

export interface Data {
	'overview-month-total': OverviewMonthTotal;
}

export interface OverviewMonthTotal {
	channel: ChannelElement[];
}

export interface ChannelElement {
	$: Channel;
	month: MonthClass;
}

export interface Channel {
	name: string;
	'meta-name': string;
	unit: string;
}

export interface MonthClass {
	$: Month;
	day?: Day[];
}

export interface Month {
	timestamp: string;
	absolute?: string;
	difference?: string;
}

export interface Day {
	$: Month;
}
