// Generated by https://quicktype.io

export interface IYearlyOverview {
	'sma.sunnyportal.services': SMASunnyportalServices;
}

export interface SMASunnyportalServices {
	service: Service;
}

export interface Service {
	$: ServiceClass;
	data: Data;
}

export interface ServiceClass {
	name: string;
	method: string;
	version: string;
	'request-oid': string;
	'creation-date': string;
}

export interface Data {
	'overview-year-total': OverviewYearTotal;
}

export interface OverviewYearTotal {
	channel: ChannelElement[];
}

export interface ChannelElement {
	$: Channel;
	year: YearClass;
}

export interface Channel {
	name: string;
	'meta-name': string;
	unit: string;
}

export interface YearClass {
	$: Year;
	month?: Month[];
}

export interface Year {
	timestamp: string;
	absolute?: string;
	difference?: string;
}

export interface Month {
	$: Year;
}
